### ISSUE TITLE
OutOfMemory Error when constructing hashes

### ISSUE THREAD

**Issue by kyle-hiller-nh** [Tinder/bazel-diff#100]
I'm using bazel-diff 3.3.0 and Bazel 4.2.1. Whenever I run the provided example script over our moderately sized Go repo, the script is able to generate the starting hashes but the second set of hashes generates the following error:

`Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOf(Arrays.java:3536)
        at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:100)
        at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:130)
        at java.base/java.io.OutputStream.write(OutputStream.java:127)
        at com.bazel_diff.BazelSourceFileTargetImpl.<init>(BazelSourceFileTarget.java:30)
        at com.bazel_diff.BazelClientImpl.processBazelSourcefileTargets(BazelClient.java:74)
        at com.bazel_diff.BazelClientImpl.queryAllSourcefileTargets(BazelClient.java:58)
        at com.bazel_diff.TargetHashingClientImpl.hashAllBazelTargetsAndSourcefiles(TargetHashingClient.java:28)
        at com.bazel_diff.GenerateHashes.call(main.java:58)
        at com.bazel_diff.GenerateHashes.call(main.java:22)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1853)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2255)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2249)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2213)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2080)
        at picocli.CommandLine.execute(CommandLine.java:1978)
        at com.bazel_diff.BazelDiff.main(main.java:169)
`

I have tried increasing the heap size available to Bazel in the startup options but I think this is an OOM from the JAR itself?

**Comment by tinder-maxwellelliott** [comment]
@fahhem This is interesting, we just merged #97 to fix this?

**Comment by fahhem** [comment]
Do you have individual files that are very large? #97 decreased the memory footprint for us by 15x, so I'd have to see what your memory usage is now. Can you run the jar with a larger heap and see what you need? Run it with `-Xmx1g -Xms1g` to give it 1 GB of heap

**Comment by pmoncadaisla** [comment]
I'm getting the following error:

```
Exception in thread "main" java.lang.OutOfMemoryError: Required array size too large
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3294)
	at com.bazel_diff.BazelSourceFileTargetImpl.<init>(BazelSourceFileTarget.java:30)
	at com.bazel_diff.BazelClientImpl.processBazelSourcefileTargets(BazelClient.java:74)
	at com.bazel_diff.BazelClientImpl.queryAllSourcefileTargets(BazelClient.java:58)
	at com.bazel_diff.TargetHashingClientImpl.hashAllBazelTargetsAndSourcefiles(TargetHashingClient.java:28)
	at com.bazel_diff.GenerateHashes.call(main.java:58)
	at com.bazel_diff.GenerateHashes.call(main.java:22)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1853)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2255)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2249)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2213)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2080)
	at picocli.CommandLine.execute(CommandLine.java:1978)
	at com.bazel_diff.BazelDiff.main(main.java:173)
```

which seems different from @kyle-hiller-nh . This one says: `Required array size too large`
I've tried to increase the heap memory with no luck.

**Comment by fahhem** [comment]
That seems like there's a specific file that's very large, and bazel-diff reads it in one go. Do you have any specifically large files?

**Comment by tinder-maxwellelliott** [comment]
Should be resolved on master
