### ISSUE TITLE
stackOverflow issue. A fix for the issue 71 fix.

### ISSUE THREAD

**Issue by tkbrex** [Tinder/bazel-diff#78]
I wonder what is the best way to debug this problem. I think it is because it cannot parse some of the rules and end up in a recursive loop. I want to find out which rule is causing the problem so maybe I can fix the rule.

==========

[2021-07-21T08:14:49Z] Exception in thread "main" java.lang.StackOverflowError
--
  | [2021-07-21T08:14:49Z] 	at java.base/java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3963)
  | [2021-07-21T08:14:49Z] 	at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4804)
  | [2021-07-21T08:14:49Z] 	at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4749)
  | [2021-07-21T08:14:49Z] 	at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4747)
  | [2021-07-21T08:14:49Z] 	at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4747)
  | [2021-07-21T08:14:49Z] 	at java.base/java.util.regex.Pattern$BranchConn.match(Pattern.java:4713)
  | [2021-07-21T08:14:49Z] 	at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:4863)
  | [2021-07-21T08:14:49Z] 	at java.base/java.util.regex.Pattern$BmpCharPropertyGreedy.match(Pattern.java:4344)
  | [2021-07-21T08:14:49Z] 	at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4804)
  | [2021-07-21T08:14:49Z] 	at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4749)
  | [2021-07-21T08:14:49Z] 	at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4747)
  | [2021-07-21T08:14:49Z] 	at java.base/java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3964)
  | [2021-07-21T08:14:49Z] 	at java.base/java.util.regex.Pattern$Start.match(Pattern.java:3619)
  | [2021-07-21T08:14:49Z] 	at java.base/java.util.regex.Matcher.search(Matcher.java:1729)
  | [2021-07-21T08:14:49Z] 	at java.base/java.util.regex.Matcher.find(Matcher.java:773)
  | [2021-07-21T08:14:49Z] 	at java.base/java.util.Formatter.parse(Formatter.java:2702)
  | [2021-07-21T08:14:49Z] 	at java.base/java.util.Formatter.format(Formatter.java:2655)
  | [2021-07-21T08:14:49Z] 	at java.base/java.util.Formatter.format(Formatter.java:2609)
  | [2021-07-21T08:14:49Z] 	at java.base/java.lang.String.format(String.java:2897)
  | [2021-07-21T08:14:49Z] 	at com.bazel_diff.BazelRuleImpl.transformRuleInput(BazelRule.java:53)
  | [2021-07-21T08:14:49Z] 	at com.bazel_diff.BazelRuleImpl.lambda$getRuleInputList$0(BazelRule.java:38)
  | [2021-07-21T08:14:49Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
  | [2021-07-21T08:14:49Z] 	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
  | [2021-07-21T08:14:49Z] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
  | [2021-07-21T08:14:49Z] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
  | [2021-07-21T08:14:49Z] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
  | [2021-07-21T08:14:49Z] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  | [2021-07-21T08:14:49Z] 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
  | [2021-07-21T08:14:49Z] 	at com.bazel_diff.BazelRuleImpl.getRuleInputList(BazelRule.java:39)
  | [2021-07-21T08:14:49Z] 	at com.bazel_diff.TargetHashingClientImpl.createDigestForRule(TargetHashingClient.java:88)
  | [2021-07-21T08:14:49Z] 	at com.bazel_diff.TargetHashingClientImpl.createDigestForRule(TargetHashingClient.java:93)
  | [2021-07-21T08:14:49Z] 	at com.bazel_diff.TargetHashingClientImpl.createDigestForRule(TargetHashingClient.java:93)
  | [2021-07-21T08:14:49Z] 	at com.bazel_diff.TargetHashingClientImpl.createDigestForRule(TargetHashingClient.java:93)
  | [2021-07-21T08:14:49Z] 	at com.bazel_diff.TargetHashingClientImpl.createDigestForRule(TargetHashingClient.java:93)
  | [2021-07-21T08:14:49Z] 	at com.bazel_diff.TargetHashingClientImpl.createDigestForRule(TargetHashingClient.java:93)
  | [2021-07-21T08:14:49Z] 	at com.bazel_diff.TargetHashingClientImpl.createDigestForRule(TargetHashingClient.java:93)
  | [2021-07-21T08:14:49Z] 	at com.bazel_diff.TargetHashingClientImpl.createDigestForRule(TargetHashingClient.java:93)
  | [2021-07-21T08:14:49Z] 	at com.bazel_diff.TargetHashingClientImpl.createDigestForRule(TargetHashingClient.java:93)
  | [2021-07-21T08:14:49Z] 	at com.bazel_diff.TargetHashingClientImpl.createDigestForRule(TargetHashingClient.java:93)
.... same call to createDigestForRule 100+ times ....

**Comment by tkbrex** [comment]
This is the same as issue 71 ( https://github.com/Tinder/bazel-diff/issues/71 ). Closed

**Comment by tkbrex** [comment]
issue #71 is fixed but it creates a new problem when inputRule.getName() = null. In the same line, we need to check for inputRUle.getName() == null. 

`             if (inputRule != null && inputRule.getName() != null && !inputRule.getName().equals(rule.getName())) {
`
