### ISSUE TITLE
NPE when -o flag is not provided

### ISSUE THREAD

**Issue by Warchant** [Tinder/bazel-diff#95]
I am getting a NullPointerException when starting hashes and final hashes are same:
UPD: it turned out that NPE is caused by lack of -o flag.
```
C:\bin>java -jar bazel-diff_deploy.jar  -w C:\W\workspace -b .\bazel.exe -sh a.txt -fh b.txt
java.lang.NullPointerException
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:228)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
        at java.base/java.io.FileWriter.<init>(FileWriter.java:96)
        at com.bazel_diff.BazelDiff.call(main.java:153)
        at com.bazel_diff.BazelDiff.call(main.java:71)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1853)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2255)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2249)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2213)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2080)
        at picocli.CommandLine.execute(CommandLine.java:1978)
        at com.bazel_diff.BazelDiff.main(main.java:169)
```
v3.2.3 - https://github.com/Tinder/bazel-diff/tree/3.2.3

**Comment by tinder-maxwellelliott** [comment]
Should be a simple enough fix, would certainly welcome any PRs!
